title: Writing Center Resource Library
theme: minima
collections:
  resources:
    output: true
    permalink: /:collection/:name


defaults:
  - scope:
      type: "resources"
    values:
      layout: resource
